USE dbo
GO
CREATE TABLE dbo.SKU 
	(
		ID INT IDENTITY PRIMARY KEY,
		Code AS ('s' + CONVERT(VARCHAR(255), ID)) UNIQUE,
		Name NVARCHAR(255)
	);

CREATE TABLE dbo.Family
	(
		ID INT IDENTITY PRIMARY KEY,
		SurName VARCHAR(255),
		BudgetValue INT
	);

CREATE TABLE dbo.Basket
	(
		ID INT IDENTITY PRIMARY KEY,
		ID_SKU INT REFERENCES dbo.SKU (ID),
		ID_Family INT REFERENCES dbo.Family (ID),
		Quantity INT CHECK (Quantity > 0),
		Value INT CHECK (Value > 0),
		PurchaseDate DATETIME DEFAULT CURRENT_TIMESTAMP,
		DiscountValue INT
	);